---
title: "Practical Machine Learning course project - Models"
author: "Greg Michalopoulos"
date: "April 12, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r train}
set.seed(12345)
rpartfit <- train(classe ~., data = rTraining, method = "rpart")
gbmfit <- train(classe ~., data = rTraining, method = "gbm", verbose = FALSE)
rffit <- train(classe ~., data = rTraining, method = "rf")
ldafit <- train(classe ~., data = rTraining, method = "lda")
save(file = ".PML2", list = c("rffit", "lmfit", "rpartfit", "gbmfit",  "ldafit"))
```

```{r specificModels}
set.seed(12345)
rfGrid <- data.frame(.mtry = 2)
rffit <- train(classe ~., data = rTraining, method = "rf", tuneGrid = rfGrid)
rpartfit <- train(classe ~., data = rTraining, method = "rpart")
gbmGrid <- data.frame(.shrinkage = 0.1, .interaction.depth = 3, .n.minobsinnode = 10, .n.trees = 50)
gbmfit <- train(classe ~., data = rTraining, method = "gbm", verbose = FALSE, tuneGrid = gbmGrid)
ldafit <- train(classe ~., data = rTraining, method = "lda")
save(file = ".PML3", list = c("rffit", "lmfit", "rpartfit", "gbmfit",  "ldafit"))
```